name: Running Build & Tests

on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: npm install

            - name: Run Site Build
              run: npm run build
          
            - name: Run Documentation Build
              run: npm run docs:build
              
            - name: Run Package Build
              run: npm run pack
                  
            - name: Run Unit Tests
              run: npm run test:unit
